# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "280c73fee950b4c11c9ce3c3253d5d6c"
name = "moad-discount-duplin-staging"
application_url = "https://moad.allurecommerce.com"
embedded = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://moad-api.allurecommerce.com/webhooks/app-uninstalled"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request" ]
  uri = "https://moad-api.allurecommerce.com/webhooks/customers-data-request"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/redact" ]
  uri = "https://moad-api.allurecommerce.com/webhooks/customers-redact"

  [[webhooks.subscriptions]]
  compliance_topics = [ "shop/redact" ]
  uri = "https://moad-api.allurecommerce.com/webhooks/shop-redact"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_customers,read_discounts,write_discounts,read_orders,unauthenticated_write_checkouts"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://moad-api.allurecommerce.com/auth/callback"
]

[pos]
embedded = true

[build]
automatically_update_urls_on_dev = true
