query CartInput {
  cart {
    attribute(key: "moad_discount_payload") {
      value
    }
    signatureAttribute: attribute(key: "moad_discount_signature") {
      value
    }
    versionAttribute: attribute(key: "moad_discount_version") {
      value
    }
    lines {
      id
      merchandise {
        __typename
        ... on ProductVariant {
          id
        }
      }
      cost {
        subtotalAmount {
          amount
        }
      }
    }
  }
  discount {
    discountClasses
  }
}
